# Generated by Django 5.0.4 on 2024-05-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaboard',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pizzaboard',
            name='size',
        ),
        migrations.CreateModel(
            name='BoardParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в руб.')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_catalog.pizzaboard')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_catalog.pizzasizes', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Параметры борта',
                'verbose_name_plural': 'Параметры борта',
                'db_table': 'board_params',
            },
        ),
    ]
